In [1]:
import numpy as np

# create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
# To shape it into a 2D array

arr2 = arr1.reshape(1, 5)

In [4]:

arr2

array([[1, 2, 3, 4, 5]])

In [9]:
a = np.arange(0, 10, 2)  # Create an array with values from 1 to 9 with a step of 2

In [11]:
a.reshape(5, 1)  # Reshape the array to have 2 rows and 5 columns

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3, 4))  # Create a 3x4 array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# identity matrix of 
mat = np.eye(3)  # Create a 3x3 identity matrix

In [20]:
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# numpy vectorized operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition of two arrays
print(arr1 + arr2)

[11 22 33 44 55]


In [22]:
print(arr2 - arr1)

[ 9 18 27 36 45]


In [ ]:
# Universal functions (ufuncs) for element-wise operations


arr = np.array([4, 9, 16, 25, 36])
print(np.sqrt(arr))
print(np.exp(arr))  # Exponential of each element in the array
print(np.log(arr)) 
print(np.sin(arr))# Natural logarithm of each element in the array
# Square root of each element in the array

[2. 3. 4. 5. 6.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15]
[1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
[-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]


In [ ]:
# array slicing and indexing
arr = np.array([[1, 2, 3, 4 ], [5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
arr[1:3, 2:] # Slicing the array to get elements from row 2 and columns 0 to 2

array([[ 7,  8],
       [11, 12]])

In [44]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [46]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [47]:
# modify array elements
arr[0, 0] = 100  # Change the first element to 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:] = 100

In [49]:
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
# statistcal concepts --- Normalization

def normalize(arr):
    """Normalize a numpy array to have mean 0 and standard deviation 1."""
    mean = np.mean(arr)
    std = np.std(arr)
    return (arr - mean) / std

In [51]:
normalized_arr = normalize([1,2,3,4,5])
print("Normalized array:", normalized_arr)

Normalized array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

array([ 6,  7,  8,  9, 10])